#######
## Spring boot server configuration
#######  
server:
   scheme: http
   host: localhost
   servlet:
      contextPath: /admission/v1
   port: ${PORT:7070}
   error:
      whitelabel:
          enabled: false

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ${KAFKA_INPUT_TOPIC:avro.topic1}
          content-type: application/*+avro
          group: group-1
        output:
          destination:  ${KAFKA_OUTPUT_TOPIC:avro.topic2}
          content-type: application/*+avro
      kafka:
          binder:
           brokers: ${KAFKA_BROKER:localhost:9092}
           autoAddPartitions: true  
           producer-properties:
             key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
             value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
             schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
           consumer-properties:
             key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
             value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
             schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
             specific.avro.reader: true
      schema:
        avro:
          dynamicSchemaGenerationEnabled: true
                     